# 1. List all unique cities where customers are located.
query = """select distinct customer_city 
           from customers"""
cursor.execute(query)
data = cursor.fetchall()
for row in data:
    print(row)

# 2. Count the number of orders placed in 2017.
query = """select count(order_id) 
           from orders 
           where order_purchase_timestamp like '%2017%'"""
cursor.execute(query)
print(f"Orders in 2017: {cursor.fetchall()[0][0]}")

# 3. Find the total sales per category.
query = """
select products.product_category,
       round(sum(payments.payment_value), 2) as total_sales
from products
join order_items
on products.product_id = order_items.product_id
join payments
on order_items.order_id = payments.order_id
group by products.product_category
"""
cursor.execute(query)
data = cursor.fetchall()
for row in data:
    print(row)

# 4. Calculate the percentage of orders that were paid in installments.
query = """
select round(sum(case when payment_installments > 1 then 1 else 0 end)/count(*) * 100, 2) as installment_percentage
from payments
"""
cursor.execute(query)
print(f"Percentage of orders paid in installments {cursor.fetchall()[0][0]}%")

# 5. Count the number of customers from each state.
query = """
select customer_state, count(customer_id) as customer_count
from customers
group by customer_state
"""
cursor.execute(query)
data = cursor.fetchall()
for row in data:
    print(row)
df = pd.DataFrame(data, columns=['customer_state', 'customer_count'])
df = df.sort_values(by='customer_count', ascending=False)
plt.figure(figsize=(12,6))
plt.bar(df['customer_state'], df['customer_count'], color='blue')
plt.xticks(rotation=90)
plt.show()

# 6. Calculate the number of orders per month in 2018.
query = """
select substring(trim(order_purchase_timestamp), 4, 2) as order_month,
       count(order_id) as order_count
from orders
where substring(trim(order_purchase_timestamp), 7, 4) = '2018'
group by order_month
order by order_month
"""
cursor.execute(query)
data = cursor.fetchall()
print("Rows returned:", len(data))
for row in data:
    print(row)

# 7. Find the average number of products per order, grouped by customer city.
query = """
with cte as (select orders.order_id, orders.customer_id, count(order_items.order_id) as oc
from orders
join order_items
on orders.order_id = order_items.order_id
group by orders.order_id, orders.customer_id)
select customers.customer_city,
        round(avg(cte.oc),2) as avg_products_per_order
from customers
join cte
on customers.customer_id = cte.customer_id
group by customers.customer_city
"""
cursor.execute(query)
data = cursor.fetchall()
for row in data:
    print(row)

# 8. Calculate the percentage of total revenue contributed by each product category.
query = """
select products.product_category,
       round((sum(payments.payment_value)/(select sum(payment_value) from payments))*100, 2) as total_sales_percentage
from products
join order_items
on products.product_id = order_items.product_id
join payments
on order_items.order_id = payments.order_id
group by products.product_category
"""
cursor.execute(query)
data = cursor.fetchall()
for row in data:
    print(row)

# 9. Identify the correlation between product price and the number of times a product has been purchased.
query = """
select products.product_category, count(order_items.product_id) as purchase_count, round(avg(order_items.price),2)
from products
join order_items
on products.product_id = order_items.product_id
group by products.product_category
"""
cursor.execute(query)
data = cursor.fetchall()
df = pd.DataFrame(data, columns=['product_category', 'purchase_count', 'avg_price'])
arr1  = df["purchase_count"]
arr2 = df["avg_price"]
print("Correlation coefficient between product price and purchase count:", np.corrcoef(arr1, arr2)[0,1])

# 10. Calculate the total revenue generated by each seller, and rank them by revenue.
query = """
select *, dense_rank() over (order by total_revenue desc) as revenue_rank
from
(select order_items.seller_id, round(sum(payments.payment_value),2) as total_revenue
from order_items
join payments
on order_items.order_id = payments.order_id
group by order_items.seller_id) as a
"""
cursor.execute(query)
data = cursor.fetchall()
for row in data:
    print(row)

# 11. Calculate the moving average of order values for each customer over their order history.
query = """
select customer_id, order_purchase_timestamp, avg(payment) over (partition by customer_id order by order_purchase_timestamp
rows between 2 preceding and current row) as moving_avg_order_value
from
(select orders.customer_id, orders.order_purchase_timestamp, payments.payment_value as payment
from payments
join orders
on payments.order_id = orders.order_id) as a
"""
cursor.execute(query)
data = cursor.fetchall()
for row in data:
    print(row)

# 12. Calculate the cumulative sales per month for each year.
query = """
select order_year, order_month, 
round(sum(payment) over (order by order_year, order_month),2) as cumulative_sales
from
(select year(orders.order_purchase_timestamp) as order_year,
       month(orders.order_purchase_timestamp) as order_month,
       round(sum(payments.payment_value),2) as payment
from orders
join payments       
on orders.order_id = payments.order_id
group by order_year, order_month
order by order_year, order_month) as a
"""
cursor.execute(query)
data = cursor.fetchall()
for row in data:
    print(row)

# 13. Calculate the year-over-year growth rate of total sales.
query = """
with cte as (select year(orders.order_purchase_timestamp) as order_year,
       round(sum(payments.payment_value),2) as payment
from orders
join payments       
on orders.order_id = payments.order_id
group by order_year
order by order_year)
select order_year, payment, 
lag(payment) over (order by order_year)
from cte
"""
cursor.execute(query)
data = cursor.fetchall()
for row in data:
    print(row)

# 14. Calculate the retention rate of customers who make another purchase within 6 months.
query = """
with cte as (select customers.customer_id,
       min(orders.order_purchase_timestamp) as first_order_date
from customers
join orders
on customers.customer_id = orders.customer_id
group by customers.customer_id),
cte1 as (select cte.customer_id, count(distinct orders.order_purchase_timestamp) as repeat_orders_within_6_months
from cte
join orders
on cte.customer_id = orders.customer_id and orders.order_purchase_timestamp > cte.first_order_date
and orders.order_purchase_timestamp <= date_add(cte.first_order_date, interval 6 month)
group by cte.customer_id)
select round((sum(case when cte1.repeat_orders_within_6_months > 0 then 1 else 0 end)/count(*) * 100),2) as retention_rate_percentage
from cte
left join cte1
on cte.customer_id = cte1.customer_id
"""
cursor.execute(query)
data = cursor.fetchall()
for row in data:
    print(row)
